package com.dhcc.nursepro.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dhcc.nursepro.login.bean.NurseInfo;

import com.dhcc.nursepro.greendao.NurseInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig nurseInfoDaoConfig;

    private final NurseInfoDao nurseInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        nurseInfoDaoConfig = daoConfigMap.get(NurseInfoDao.class).clone();
        nurseInfoDaoConfig.initIdentityScope(type);

        nurseInfoDao = new NurseInfoDao(nurseInfoDaoConfig, this);

        registerDao(NurseInfo.class, nurseInfoDao);
    }
    
    public void clear() {
        nurseInfoDaoConfig.clearIdentityScope();
    }

    public NurseInfoDao getNurseInfoDao() {
        return nurseInfoDao;
    }

}
