package com.dhcc.module.infusion.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dhcc.module.infusion.db.InfusionInfo;

import com.dhcc.module.infusion.greendao.InfusionInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig infusionInfoDaoConfig;

    private final InfusionInfoDao infusionInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        infusionInfoDaoConfig = daoConfigMap.get(InfusionInfoDao.class).clone();
        infusionInfoDaoConfig.initIdentityScope(type);

        infusionInfoDao = new InfusionInfoDao(infusionInfoDaoConfig, this);

        registerDao(InfusionInfo.class, infusionInfoDao);
    }
    
    public void clear() {
        infusionInfoDaoConfig.clearIdentityScope();
    }

    public InfusionInfoDao getInfusionInfoDao() {
        return infusionInfoDao;
    }

}
